### ISSUE TITLE
Is matlab required？

### ISSUE THREAD

**Issue by Supporon** [AprilCal/TSAGen#1]
I see that matlab is called in the usage examples. Does the program have to use matlab?

**Comment by AprilCal** [comment]
> 
Matlab is required only if you want to use the pearson distribution. You can avoid installing matlab by using Gaussian distribution as the noise generator. In addition, this repository will not be updated, please use the latest version in https://github.com/Lab-ANT/TSAGen

Feel free to submit an issue if you encounter any problem when using TSAGen.

**Comment by AprilCal** [comment]
> Matlab is required only if you want to use the pearson distribution. You can

Matlab is required only if you want to use the pearson distribution. You can avoid installing matlab by using Gaussian distribution as the noise generator. In addition, this repository will not be updated, please use the latest version in https://github.com/Lab-ANT/TSAGen

Feel free to submit an issue if you encounter any problem when using TSAGen.

**Comment by Supporon** [comment]
> > Matlab is required only if you want to use the pearson distribution. You can
> 
> Matlab is required only if you want to use the pearson distribution. You can avoid installing matlab by using Gaussian distribution as the noise generator. In addition, this repository will not be updated, please use the latest version in https://github.com/Lab-ANT/TSAGen
> 
> Feel free to submit an issue if you encounter any problem when using TSAGen.

thanks for the reply, this work has been very useful and inspiring to me.
In contrast to using the pearson distribution, using Gaussian distribution as the noise generator.How much influence does it have on the performance of the generated KPIs? 
In addition, the reason for using matlab is that python cannot generate the pearson distribution?
